markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Basic  
exclude: ['README.md']
title: 宋运龙 ／ Yunlong Song 
subtitle: 个人站 / Personal Website
description: Welcome to my Personal Website
# 头像里面的标题
avatarTitle: 生活就是远方
# 头像里面的描述
avatarDesc: Learning
url: "yun-long.github.io/"

# Comment
comment:
    duoshuo: Yunlon Song

# Social
social:
    weibo: 5164254284
    github: yun-long
    twitter: Cprimer_
    mail: yun-long.song@outlook.com

#markdown: kramdown

#kramdown:
  #input: GFM
  #syntax_highlighter: rouge


permalink: /:year/:month/:title/
# Format

textColor: #FFFFFF

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog

# Navigation buttons in the front page.s
nav:
    - {title: Archive, description: archive, url: '/archive'}   
    - {title: CV, description: CV, url: '/pdf/CV.pdf'}      
    - {title: About, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


