(function(g){var window=this;var uva=function(a,b){var c=[];g.Vk(b,function(a){var b;try{b=g.Om.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.Yh(b)&&c.push(a):c.push(a)},a);
return c},vva=function(a,b){var c=uva(a,b);
(0,g.L)(c,function(a){g.Om.prototype.remove.call(this,a)},a)},j9=function(a,b){g.f_.call(this,g.M("YTP_MDX_TITLE"),0,a,b);
this.X=a;this.F={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},wva=function(){var a=g.Fv;
vva(a,a.g.Nd(!0))},xva=function(a){return a.H?a.F+((0,g.D)()-a.A)/1E3:a.F},k9=function(a){g.Pi("cloudview",a)},l9=function(a){g.Iu.call(this,"ScreenServiceProxy");
this.Uc=a;this.o=[];this.o.push(this.Uc.$_s("screenChange",(0,g.B)(this.xQ,this)));this.o.push(this.Uc.$_s("onlineScreenChange",(0,g.B)(this.TM,this)))},yva=function(a){k9("setApiReady_ "+a);
g.v("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m9=function(){return g.w("yt.mdx.remote.cloudview.instance_")},zva=function(a){g.is[a]&&(a=g.is[a],(0,g.L)(a,function(a){g.gs[a]&&delete g.gs[a]}),a.length=0)},n9=function(){return g.w("yt.mdx.remote.connection_")},o9=function(a){g.v("yt.mdx.remote.connectData_",a,void 0)},Ava=function(a){g.v("yt.mdx.remote.currentScreenId_",a,void 0)},p9=function(){return g.w("yt.mdx.remote.currentScreenId_")},r9=function(){if(!q9){var a=g.w("yt.mdx.remote.screenService_");
q9=a?new l9(a):null}return q9},s9=function(a){g.v("yt.mdx.remote.cloudview.initializing_",a,void 0)},t9=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},u9=function(a){k9("setCastInstalled_ "+a);
g.Hv("yt-remote-cast-installed",a)},v9=function(a){g.Pi("cloudview",a)},Bva=function(a,b){m9().init(a,b)},w9=function(){return!!g.Iv("yt-remote-cast-installed")},Cva=function(){k9("dispose");
var a=m9();a&&a.dispose();g.v("yt.mdx.remote.cloudview.instance_",null,void 0);yva(!1);g.ks(x9);x9.length=0},Dva=function(){var a=window.document.createElement("a");
g.Ln(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.ic(a)},Eva=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Fva=function(a){var b=g.fs();
if(b)if(b.clear(a),a)zva(a);else for(var c in g.is)zva(c)},y9=function(){return g.w("yt.mdx.remote.channelParams_")||{}},A9=function(a){var b=n9();
o9(null);a||Ava("");g.v("yt.mdx.remote.connection_",a,void 0);z9&&((0,g.L)(z9,function(b){b(a)}),z9.length=0);
b&&!a?g.ns("yt-remote-connection-change",!1):!b&&a&&g.ns("yt-remote-connection-change",!0)},Gva=function(){return g.w("yt.mdx.remote.connectData_")},B9=function(){var a=p9();
if(!a)return null;var b=r9().Sd();return g.pl(b,a)},Hva=function(a,b){u9(!0);
s9(!1);Bva(a,function(a){a?(yva(!0),g.ls("yt-remote-cast2-api-ready")):(v9("Failed to initialize cast API."),u9(!1),g.Jv("yt-remote-cast-available"),g.Jv("yt-remote-cast-receiver"),Cva());b(a)})},Iva=function(){return w9()?m9()?m9().getCastSession():(v9("getCastSelector: Cast is not initialized."),null):(v9("getCastSelector: Cast API is not installed!"),null)},Jva=function(){var a=Dva(),b=window.document.getElementById(a),c=b&&g.Bc(b,"loaded");
c||b&&!c||(b=Eva(a,function(){g.Bc(b,"loaded")||(g.Cc(b,"loaded","true"),g.ls(a),g.Zj(g.ya(Fva,a),0))}))},Kva=function(a){return(0,g.O)(a,function(a){return{key:a.id,
name:a.name}})},Lva=function(){if(g.qoa){var a=2,b=g.Da(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Ia("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Fa,c)}},D9=function(a,b){p9();
B9()&&B9();Ava(a.id);var c=new g.sO(C9,a,y9());c.connect(b,Gva());c.subscribe("beforeDisconnect",function(a){g.ns("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){n9()&&(n9(),A9(null))});
A9(c)},E9=function(){var a=g.Ax();
if(!a)return null;var b=r9().Sd();return g.pl(b,a)},F9=function(a){g.Pi("remote",a)},G9=function(){var a=n9();
return!!a&&3!=a.getProxyState()},H9=function(){t9()?m9().stopSession():v9("stopSession called before API ready.");
var a=n9();a&&(a.disconnect(1),A9(null))},Mva=function(){var a;
a=r9().Uc.$_gos();var b=B9();b&&n9()&&(g.ol(a,b)||a.push(b));return Kva(a)},J9=function(a,b){g.es.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.ai;this.A=this.o=null;this.H=(0,g.B)(this.dL,this);this.F=(0,g.B)(this.Ak,this);this.G=(0,g.B)(this.cL,this);this.J=(0,g.B)(this.qL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.qt,this),Nva(this))):c=3;0!=c&&(b?this.qt(c):g.Zj((0,g.B)(function(){this.qt(c)},this),0));
var d=Iva();d&&I9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},K9=function(a){return new g.be(a.B.getPlayerContextData())},Ova=function(a,b,c,d,e){var f=K9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.fe(f,b,d);g.t(c)&&(g.de(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);L9(a,"setPlaylist",l);e||M9(a,f)},Nva=function(a){(0,g.L)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.ya(this.nN,a),this))},a)},Pva=function(a){(0,g.L)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},N9=function(a,b){50>a.C.Dc()&&g.ci(a.C,b)},O9=function(a,b,c){var d=K9(a);
g.de(d,c);-1E3!=d.g&&(d.g=b);M9(a,d)},L9=function(a,b,c){a.B.sendMessage(b,c)},M9=function(a,b){Pva(a);
a.B.setPlayerContextData(g.ge(b));Nva(a)},I9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Ak(null));
a.A=b;a.A&&(P9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Ak(a.A.media[0]))},Qva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=K9(a);b.contentId!=d.videoId&&P9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.de(d,a.o.getEstimatedTime());M9(a,d)}else P9("No cast media video. Ignoring state update.")},P9=function(a){g.Pi("CP",a)},Q9=function(a,b,c){return(0,g.B)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),L9(this,b,c))},a)},Rva=function(a){var b=!1;
m9()||(a=new g.oL(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Hv("yt-remote-cast-available",a);g.ns("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){k9("onReceiverSelected: "+a.friendlyName);
g.Hv("yt-remote-cast-receiver",a);g.ns("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){k9("onReceiverResumed: "+a.friendlyName);
g.Hv("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){k9("onSessionChange: "+g.Xi(a));
a||g.Jv("yt-remote-cast-receiver");g.ns("yt-remote-cast2-session-change",a)}),g.v("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
k9("cloudview.createSingleton_: "+b);return b},Sva=function(){var a=0<=g.Jd.search(/\ (CrMo|Chrome|CriOS)\//);
return g.ip||a},R9=function(a,b){t9()?m9().setConnectedScreenStatus(a,b):v9("setConnectedScreenStatus called before ready.")},Tva=function(){k9("clearCurrentReceiver");
g.Jv("yt-remote-cast-receiver")},Uva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Lva();a({command:"cast.sender.init"});return}}if(window.chrome)if(Lva(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Ba();55<=b?a="55":50<=b&&(a="50");g.Ia("//www.gstatic.com/eureka/clank"+a+g.Ga,g.Fa)}else g.Ja(0);else g.Fa()},Vva=function(a){a?(g.Hv("yt-remote-session-app",a.app),g.Hv("yt-remote-session-name",a.name)):(g.Jv("yt-remote-session-app"),g.Jv("yt-remote-session-name"));
g.v("yt.mdx.remote.channelParams_",a,void 0)},Wva=function(){var a=y9();
if(g.Hb(a)){var a=g.zx(),b=g.Iv("yt-remote-session-name")||"",c=g.Iv("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.v("yt.mdx.remote.channelParams_",a,void 0)}},Xva=function(){var a=E9();
a?(F9("Resume connection to: "+g.Xi(a)),D9(a,0)):(g.Ix(),Tva(),F9("Skipping connecting because no session screen found."))},Yva=function(a){F9("remote.onCastSessionChange_: "+g.Xi(a));
if(a){var b=B9();b&&b.id==a.id?R9(b.id,"YouTube TV"):(b&&H9(),D9(a,1))}else n9()&&H9()},Zva=function(){var a=Mva(),b=B9();
b||(b=E9());return g.we(a,function(a){return b&&g.Ui(b,a.key)?!0:!1})},$va=function(){var a=g.Iv("yt-remote-cast-receiver");
return a?a.friendlyName:null},awa=function(a,b,c,d){Sva()?Rva(b)&&(s9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Hva(a,c):(window.__onGCastApiAvailable=function(b,d){b?Hva(a,c):(v9("Failed to load cast API: "+d),u9(!1),s9(!1),g.Jv("yt-remote-cast-available"),g.Jv("yt-remote-cast-receiver"),Cva(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Jva():Uva())):k9("Cannot initialize because not running Chrome")},
bwa=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.zf(a)||"";b&&(this.port=":"+b);this.A=g.yf(a)||"";a=g.Jd;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.hc(a,"10.0")&&(this.o=!1))},S9=function(){var a=Zva();
!a&&w9()&&$va()&&(a={key:"cast-selector-receiver",name:$va()});return a},cwa=function(){var a=Mva();
w9()&&g.Iv("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},dwa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.Fv&&wva();g.Cx();C9||(C9=new bwa,g.Kx()&&(C9.g="/api/loungedev"));z9||(z9=g.w("yt.mdx.remote.deferredProxies_")||[],g.v("yt.mdx.remote.deferredProxies_",z9,void 0));Wva();var c=r9();if(!c){var d=new g.uF(C9);g.v("yt.mdx.remote.screenService_",d,void 0);c=r9();awa(a,d,function(a){a?p9()&&R9(p9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.ns("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.w("yt.mdx.remote.initialized_")&&
(g.v("yt.mdx.remote.initialized_",!0,void 0),F9("Initializing: "+g.ob(b)),T9.push(g.js("yt-remote-cast2-availability-change",function(){g.ns("yt-remote-receiver-availability-change")})),T9.push(g.js("yt-remote-cast2-receiver-selected",function(){o9(null);
g.ns("yt-remote-auto-connect","cast-selector-receiver")})),T9.push(g.js("yt-remote-cast2-receiver-resumed",function(){g.ns("yt-remote-receiver-resumed","cast-selector-receiver")})),T9.push(g.js("yt-remote-cast2-session-change",Yva)),T9.push(g.js("yt-remote-connection-change",function(a){a?R9(p9(),"YouTube TV"):E9()||(R9(null,null),Tva())})),a=y9(),b.isAuto&&(a.id+="#dial"),g.Vf("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,F9(" -- with channel params: "+g.ob(a)),
Vva(a),c.start(),p9()||Xva())},U9=function(){w9()?m9()?t9()?(k9("Requesting cast selector."),m9().requestSession()):(k9("Wait for cast API to be ready to request the session."),x9.push(g.js("yt-remote-cast2-api-ready",U9))):v9("requestCastSelector: Cast is not initialized."):v9("requestCastSelector: Cast API is not installed!")},V9=function(a,b,c){g.J.call(this);
this.H=a;this.X=b;b.addEventListener("onVolumeChange",this.xn,this);b.addEventListener("onCaptionsTrackListChanged",this.vz,this);b.addEventListener("captionschanged",this.hz,this);b.addEventListener("captionssettingschanged",this.Cs,this);b.addEventListener("videoplayerreset",this.Dk,this);b.addEventListener("mdxautoplaycancel",this.dv,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.Iz,this);c.subscribe("remotePlayerChange",this.Ck,this);c.subscribe("remoteQueueChange",this.Dk,this);
c.subscribe("autoplayUpNext",this.fz,this);c.subscribe("previousNextChange",this.Fz,this);c.subscribe("nowAutoplaying",this.yz,this);c.subscribe("autoplayDismissed",this.ez,this);this.suggestion=null;this.D=new g.YH(64);this.o=new g.qz(this.SA,500,this);g.K(this,this.o);this.A=new g.qz(this.TA,1E3,this);g.K(this,this.A);this.B={};this.G=new g.qz(this.hB,1E3,this);g.K(this,this.G);this.F=new g.tz(this.oS,1E3,this);g.K(this,this.F);this.J=g.y;this.Cs();this.Dk();this.Ck()},W9=function(a,b){var c=a.H,
d=a.X.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},ewa=function(a){W9(a,0);
a.o.stop();X9(a,new g.YH(64))},$9=function(a,b){if(Y9(a)&&!a.C){var c=null;
b&&(c={style:a.X.bl()},g.Nb(c,b));a.g.MA(Z9(a),c);a.B=K9(a.g).o}},a$=function(a,b){var c=a.X.Wf();
c?Ova(a.g,Z9(a),b,c.Qd(),c.listId.toString()):Ova(a.g,Z9(a),b);X9(a,new g.YH(1))},fwa=function(a,b){if(b){var c=a.X.Xc("captions","tracklist",{yx:1});
c&&c.length?(a.X.Fe("captions","track",b),a.C=!1):(a.X.Xk("captions"),a.C=!0)}else a.X.Fe("captions","track",{})},Y9=function(a){return K9(a.g).videoId==Z9(a)},Z9=function(a){return a.X.getVideoData().videoId},X9=function(a,b){a.A.stop();
var c=a.D;if(!g.dI(c,b)){var d=g.H(b,2);if(d!=g.H(a.D,2)){var e=a.X;(e=g.aY(e.app,e.playerType||1))&&g.XW(e,d)}a.D=b;gwa(a.H,c,b)}},b$=function(a){g.W.call(this,{K:"div",
Y:"ytp-remote",R:[{K:"div",Y:"ytp-remote-display-status",R:[{K:"div",Y:"ytp-remote-display-status-icon",R:[g.pi()]},{K:"div",Y:"ytp-remote-display-status-text",R:["{{statustext}}"]}]}]});this.g=new g.QC(this,250);g.K(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);hwa(this,g.XF(a))},hwa=function(a,b){if(3==a.A.Xa()){var c={RECEIVER_NAME:a.A.Xc("remote","currentReceiver").name},c=g.H(b,128)?g.M("YTP_MDX_STATUS_ERROR_2",c):b.tb()||g.H(b,4)?g.M("YTP_MDX_STATUS_PLAYING_2",c):g.M("YTP_MDX_STATUS_CONNECTED_2",
c);
a.Ea("statustext",c);a.g.show()}else g.SC(a.g)},c$=function(a){g.Su.call(this,a);
this.A={key:g.nl(),name:g.M("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.YH(64);this.H=0;var b=g.VX(a).C;b&&(b=b.A&&b.A.g)&&(b=new j9(a,b),g.K(this,b));b=new b$(a);g.K(this,b);g.qY(a,b.element,5)},gwa=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.ad(c,b))},d$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)H9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.Wf();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Zb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.EB(),0),currentTime:a.g.getCurrentTime()}}else c=null;F9("Connecting to: "+g.ob(b));"cast-selector-receiver"==b.key?(o9(c||null),c=c||null,t9()?m9().setLaunchParams(c):v9("setLaunchParams called before ready.")):!c&&G9()&&p9()==b.key?g.ns("yt-remote-connection-change",
!0):(H9(),o9(c||null),c=r9().Sd(),(c=g.pl(c,b.key))&&D9(c,1))}};
g.p(j9,g.f_);j9.prototype.H=function(){var a=this.X.Xc("remote","receivers");a&&1<a.length&&!this.X.Xc("remote","quickCast")?(this.F=g.Ve(a,this.B,this),g.h_(this,(0,g.O)(a,this.B)),a=this.X.Xc("remote","currentReceiver"),g.g_(this,this.B(a)),this.enable(!0)):this.enable(!1)};
j9.prototype.B=function(a){return a.key};
j9.prototype.Me=function(a){return"cast-selector-receiver"==a?g.M("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
j9.prototype.gd=function(a){g.f_.prototype.gd.call(this,a);this.X.Fe("remote","currentReceiver",this.F[a]);this.A.Vb()};
g.C(l9,g.Iu);g.h=l9.prototype;g.h.Sd=function(a){return this.Uc.$_gs(a)};
g.h.contains=function(a){return!!this.Uc.$_c(a)};
g.h.get=function(a){return this.Uc.$_g(a)};
g.h.start=function(){this.Uc.$_st()};
g.h.so=function(a,b,c){this.Uc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Uc.$_r(a,b,c)};
g.h.eo=function(a,b,c,d){this.Uc.$_un(a,b,c,d)};
g.h.O=function(){for(var a=0,b=this.o.length;a<b;++a)this.Uc.$_ubk(this.o[a]);this.o.length=0;this.Uc=null;l9.P.O.call(this)};
g.h.xQ=function(){this.U("screenChange")};
g.h.TM=function(){this.U("onlineScreenChange")};
var q9=null,x9=[],z9=null,C9=null;g.C(J9,g.es);g.h=J9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,Q9(this,"play")):L9(this,"play"),O9(this,1,g.ee(K9(this))),this.U("remotePlayerChange")):N9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,Q9(this,"pause")):L9(this,"pause"),O9(this,2,g.ee(K9(this))),this.U("remotePlayerChange")):N9(this,this.pause)};
g.h.sB=function(a){if(1==this.g){if(this.o){var b=K9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.tb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,Q9(this,"seekTo",{newTime:a}))}else L9(this,"seekTo",{newTime:a});O9(this,3,a);this.U("remotePlayerChange")}else N9(this,g.ya(this.sB,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,Q9(this,"stopVideo")):L9(this,"stopVideo");var a=K9(this);a.index=-1;a.videoId="";g.ce(a);M9(this,a);this.U("remotePlayerChange")}else N9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=K9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.B)(function(){P9("set receiver volume: "+d)},this),(0,g.B)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.B)(function(){P9("set receiver muted: "+b)},this),(0,g.B)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);L9(this,"setVolume",e)}c.muted=b;c.volume=a;M9(this,c)}else N9(this,g.ya(this.setVolume,a,b))};
g.h.MA=function(a,b){if(1==this.g){var c=K9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.ob(b.style),g.Nb(d,c.o));L9(this,"setSubtitlesTrack",d);M9(this,c)}else N9(this,g.ya(this.MA,a,b))};
g.h.lt=function(a,b){if(1==this.g){L9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Kc.id});var c=K9(this);c.audioTrackId=b.Kc.id;M9(this,c)}else N9(this,g.ya(this.lt,a,b))};
g.h.rB=function(a,b){if(1==this.g){if(a&&b){var c=K9(this);g.fe(c,a,b);M9(this,c)}L9(this,"previous")}else N9(this,g.ya(this.rB,a,b))};
g.h.qB=function(a,b){if(1==this.g){if(a&&b){var c=K9(this);g.fe(c,a,b);M9(this,c)}L9(this,"next")}else N9(this,g.ya(this.qB,a,b))};
g.h.Sv=function(){1==this.g?L9(this,"dismissAutoplay"):N9(this,this.Sv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}J9.P.dispose.call(this)};
g.h.O=function(){Pva(this);this.B=null;this.C.clear();I9(this,null);J9.P.O.call(this)};
g.h.qt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.di(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.nN=function(a,b){this.U(a,b)};
g.h.dL=function(a){if(!a)this.Ak(null),I9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=K9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)P9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,M9(this,b)}};
g.h.Ak=function(a){P9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Qva(this),this.U("remotePlayerChange")};
g.h.cL=function(a){a?(Qva(this),this.U("remotePlayerChange")):this.Ak(null)};
g.h.qL=function(){var a=Iva();a&&I9(this,a)};
g.h.gc=function(a){g.Pi("CP",a)};
var T9=[];g.h=bwa.prototype;g.h.Gh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Hf(d+a,b||{})};
g.h.kt=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Jb:g.ya(this.sQ,c,!0),onError:g.ya(this.rQ,d),Vc:g.ya(this.tQ,d)};b&&(c.Pb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Nx(a,c)};
g.h.sQ=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.rQ=function(a,b){a(Error("Request error: "+b.status))};
g.h.tQ=function(a){a(Error("request timed out"))};
g.C(V9,g.J);g.h=V9.prototype;
g.h.O=function(){V9.P.O.call(this);this.o.stop();this.A.stop();this.J();this.X.removeEventListener("onVolumeChange",this.xn,this);this.X.removeEventListener("onCaptionsTrackListChanged",this.vz,this);this.X.removeEventListener("captionschanged",this.hz,this);this.X.removeEventListener("videoplayerreset",this.Dk,this);this.X.removeEventListener("captionssettingschanged",this.Cs,this);this.X.removeEventListener("mdxautoplaycancel",this.dv,this);this.g.unsubscribe("proxyStateChange",this.Iz,this);this.g.unsubscribe("remotePlayerChange",
this.Ck,this);this.g.unsubscribe("remoteQueueChange",this.Dk,this);this.g.unsubscribe("autoplayUpNext",this.fz,this);this.g.unsubscribe("previousNextChange",this.Fz,this);this.g.unsubscribe("nowAutoplaying",this.yz,this);this.g.unsubscribe("autoplayDismissed",this.ez,this);this.g=this.H=null};
g.h.gC=function(a,b){2==this.g.g||(Y9(this)?this.OG.apply(this,arguments):this.KG.apply(this,arguments))};
g.h.hz=function(a){this.gC("control_subtitles_set_track",g.Hb(a)?null:a)};
g.h.Cs=function(){var a=this.X.Xc("captions","track");g.Hb(a)||$9(this,a)};
g.h.KG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":a$(this,this.X.getCurrentTime());break;case "control_seek":a$(this,c[0]);break;case "control_subtitles_set_track":$9(this,c[0]);break;case "control_set_audio_track":c=c[0],Y9(this)&&this.g.lt(Z9(this),c)}};
g.h.OG=function(a,b){if(1081!=K9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":K9(this.g).tb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Ji(c[0],c[1]);break;case "control_subtitles_set_track":$9(this,c[0]);break;case "control_set_audio_track":c=c[0],Y9(this)&&this.g.lt(Z9(this),c)}}};
g.h.xn=function(a){if(Y9(this)){this.g.unsubscribe("remotePlayerChange",this.Ck,this);var b=Math.round(a.volume);a=!!a.muted;var c=K9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Ck,this)}};
g.h.vz=function(){g.Hb(this.B)||fwa(this,this.B);this.C=!1};
g.h.Iz=function(a,b){this.A.stop();2==b&&this.TA()};
g.h.Ck=function(){if(Y9(this)){this.o.stop();var a=K9(this.g);switch(a.g){case 1081:X9(this,new g.YH(8));break;case 1:this.SA();X9(this,new g.YH(8));break;case 1083:case 3:X9(this,new g.YH(9));break;case 0:X9(this,new g.YH(2));this.F.stop();W9(this,this.X.getVideoData().lengthSeconds);break;case 1082:X9(this,new g.YH(4));break;case 2:X9(this,new g.YH(4));W9(this,g.ee(a));break;case -1:X9(this,new g.YH(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.M("YTP_MDX_PLAYER_ERROR")},X9(this,
new g.YH(128,a))}var a=K9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,fwa(this,a));a=K9(this.g);-1==a.volume||Math.round(this.X.getVolume())==a.volume&&this.X.De()==a.muted||this.G.isActive()||this.hB()}else ewa(this)};
g.h.Fz=function(){this.X.U("mdxpreviousnextchange")};
g.h.Dk=function(){Y9(this)||ewa(this)};
g.h.dv=function(){this.g.Sv()};
g.h.fz=function(a){a&&(a=g.Nx("/watch_queue_ajax",{method:"GET",Oc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.B)(this.oO,this)}))&&(this.J=(0,g.B)(a.abort,a))};
g.h.oO=function(a,b){var c=new g.uV({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.X.U("mdxautoplayupnext",c)};
g.h.yz=function(a){(0,window.isNaN)(a)||this.X.U("mdxnowautoplaying",a)};
g.h.ez=function(){this.X.U("mdxautoplaycanceled")};
g.h.oS=function(a,b){-1==K9(this.g).g?a$(this,a):b&&this.g.sB(a)};
g.h.hB=function(){if(Y9(this)){var a=K9(this.g);this.X.removeEventListener("onVolumeChange",this.xn,this);a.muted?this.X.mute():this.X.yg();this.X.setVolume(a.volume);this.X.addEventListener("onVolumeChange",this.xn,this)}};
g.h.SA=function(){this.o.stop();if(!this.g.la()){var a=K9(this.g);a.tb()&&X9(this,new g.YH(8));W9(this,g.ee(a));this.o.start()}};
g.h.TA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};g.p(b$,g.W);b$.prototype.B=function(a){hwa(this,a.state)};g.C(c$,g.Su);g.h=c$.prototype;g.h.create=function(){dwa("embedded"==g.Y(this.g).g);this.D.push(g.js("yt-remote-before-disconnect",this.ZK,this));this.D.push(g.js("yt-remote-connection-change",this.xN,this));this.D.push(g.js("yt-remote-receiver-availability-change",this.Gz,this));this.D.push(g.js("yt-remote-auto-connect",this.vN,this));this.D.push(g.js("yt-remote-receiver-resumed",this.uN,this));this.Gz()};
g.h.load=function(){this.g.Fp();c$.P.load.call(this);this.C=new V9(this,this.g,this.o);var a;a=(a=Gva())?a.currentTime:0;var b=G9()?new J9(n9(),void 0):null;0==a&&b&&(a=g.ee(K9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));gwa(this,this.F,this.F);g.w2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Gd(this.C,this.o);this.o=this.C=null;c$.P.unload.call(this);g.w2(this.g.app,5)};
g.h.O=function(){g.ks(this.D);c$.P.O.call(this)};
g.h.il=function(a,b){this.loaded&&this.C.gC.apply(this.C,arguments)};
g.h.pG=function(){return this.loaded?this.C.suggestion:null};
g.h.Bf=function(){return this.o?K9(this.o).Bf:!1};
g.h.hasNext=function(){return this.o?K9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.TR=function(){var a=K9(this.o),b=this.g.getVideoData(),c=this.g.Cd(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.D)()-a.A)/1E3:a.B;var l=1>=xva(a)-this.getCurrentTime(),m=a.J,n=xva(a),a=0<a.C?a.C+((0,g.D)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.UR=function(){this.o&&this.o.qB()};
g.h.VR=function(){this.o&&this.o.rB()};
g.h.ZK=function(a){1==a&&(this.J=this.o?K9(this.o):null)};
g.h.xN=function(){var a=G9()?new J9(n9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Fd(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.BB(a.videoId,g.ee(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Gz=function(){this.G=[this.A].concat(cwa());var a=S9()||this.A;d$(this,a);this.g.xa("onMdxReceiversChange")};
g.h.vN=function(){var a=S9();d$(this,a)};
g.h.uN=function(){this.B=S9()};
g.h.SR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?U9():d$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&U9(),!0):!1}};
g.h.WR=function(){L9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ze=function(){return!1};window._exportCheck==g.Aa&&g.v("ytmod.player.remote",c$,void 0);})(_yt_player);
